### PR TITLE
Add option to create custom docker-compose for local changes

### LINKED ISSUE #44: Add option to create custom docker-compose for local changes
Currently it's not easily possible to make changes to the local setup without modifying the code checked in to this project.

We should allow for a custom docker-compose file anyone could create to overwrite default containers, or add new containers if needed.

We should also find solutions for config files which someone might want to adjust locally.

### PR DESCRIPTION
**Pull request by markmetcalfe**
Fixes #44

### CODE REVIEW

**Comment by derschatta** [comment]
nice one. you could add an example .yml.dist file for example overriding the port of nginx or postgres

**Comment by markmetcalfe** [comment]
Yeah it isn't overriding the port, just adding a new one. Do you think its sufficient for an example though?

**Comment by derschatta** [comment]
> Yeah it isn't overriding the port, just adding a new one. Do you think its sufficient for an example though?

that's a shame. it would give the wrong impression and people would think it would work. I would change it. Maybe add a custom volume mount or so

**Comment by markmetcalfe** [comment]
> > Yeah it isn't overriding the port, just adding a new one. Do you think its sufficient for an example though?
> 
> that's a shame. it would give the wrong impression and people would think it would work. I would change it. Maybe add a custom volume mount or so

Done

**Pull request merged**
