### PR TITLE
Update readme with uptodate Tui info and fix formatting

### PR DESCRIPTION
**Pull request by davewallace**
- config.php sample
- npm commands
- normalise trailing whitespace
- fix postgres typos

### CODE REVIEW

**Comment by derschatta** [comment]
sry @davewallace just only found time to look at this. Could you update the tui commands to the current version, they are a bit outdated now

**Comment by davewallace** [comment]
All good @derschatta - second commit good to go now

**Comment by derschatta** [comment]
sorry, @davewallace  some conflicts need to be resolved now, just merged another patch modifying the readme

**Review by derschatta — APPROVED** [review]

**Comment by derschatta** [comment]
sorry, was about to merge this but now there are conflicts, if you solve them @davewallace I'll merge it

**Comment by markmetcalfe** [comment]
No longer needed as we are using the wiki for documentation now

**Pull request closed without merging**
