### PR TITLE
Remove HOST_IP in favor of host-gateway

### PR DESCRIPTION
**Pull request by markmetcalfe**
Implementation of the fix @codyfinegan mentioned in #8

TODO: Need to properly test that this works across both Mac and Linux

### CODE REVIEW

**Comment by machine-without-the-e** [comment]
Ah I have docker dev running on a linux VM and host.docker.internal didn't work for me

**Comment by AaronMachin** [comment]
Ah I've tested this on a linux VM and it doesn't resolve to the host. Probably a useful variable to keep, at least for the time being.

**Comment by markmetcalfe** [comment]
> Ah I've tested this on a linux VM and it doesn't resolve to the host. Probably a useful variable to keep, at least for the time being.

@AaronMachin That was happening after `tup`ping the php-debug container(s) again?

**Comment by scq** [comment]
Working for me inside WSL2. Connecting to XDebug works, and I can use the `host.docker.internal` hostname from inside the container:

```
> tzsh php-8.3-debug
> curl host.docker.internal                               
<html>
<head><title>Index of /</title></head>
<body>
...
```

**Comment by AaronMachin** [comment]
@markmetcalfe ah yep it's working - just a weird issue with my vm setup. However, I do actively use this variable to achieve my VM setup. If it was removed I would have to set this up manually

**Comment by AaronMachin** [comment]
No idea how to approve on here haha! Happy with the changes

**Comment by markmetcalfe** [comment]
Hmm I've had inconsistent results getting this to work on Mac - I think there still isn't really a good solution that supports all OSes at the moment.

**Pull request closed without merging**
