### PR TITLE
Apache configuration fixes

### LINKED ISSUE #207: Remote server rewrite rules accidentally blocking valid directories for apache
The config file apache/config/remote-server.conf includes the lines:

```
# Don't allow the following files/directories to be accessed
RewriteRule (cli|tests|db|lang|classes|amd\/src|rb_sources|yui\/src) - [R=404]
RewriteRule \.(txt|md|json|xml|mustache) - [R=404]
RewriteRule \/\. - [R=404]
```

In a recent feature we added a folder 'totara/api/client/' and this is being caught by the 'cli' part of this rule because it's doing substring matching. This leads to 404 errors when you try to view that page.

We might want to match against full folder names by including a leading and trailing slash in the rule.

### LINKED ISSUE #208: Apache server drops authorization header when served over https
Apparently apache's default config is to drop the authorization header for https requests for security reasons (?). See here for more information:

https://stackoverflow.com/questions/26475885/authorization-header-missing-in-php-post-request
https://stackoverflow.com/questions/37158714/enable-apache-http-authorization-header

This breaks our external API authorization when served via apache over https (e.g. when using ngrok), because the header is stripped.

Adding the following code to apache/config/remote-server.conf fixes the issue:
```
# Don't strip Authorization header
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```
probably makes sense to include this in the config by default.

### PR DESCRIPTION
**Pull request by derschatta**
fixes #208 
fixes #207

### CODE REVIEW

**Comment by derschatta** [comment]
@simoncoggins could you test the changes?

**Comment by simoncoggins** [comment]
Fix for #208 is working well, but fix for #207 is wrong.

**Comment by derschatta** [comment]
@simoncoggins pushed a new patch up. please have another look. I've tested it locally (ngrok) and it seems to work as expected.

**Review by simoncoggins — APPROVED** [review]
Confirmed rewrite rule is working, the following path is accessible in apache via local site but not via ngrok:
totara/core/amd/src/grid.js
Confirmed client path is accessible in both:
totara/api/client/index.php
One oddity, this CLI path is not accessible in either:
totara/api/client/cli/prep_api_docs.php
I would expect it to be available locally because change is in remote-server.conf only.

API requests are working on apache with patch.
If I modify to remove the Authorization rewrite rule in the patch and rebuild, I get the error. So it's definitely working.

Passing as it's definitely doing what's expected.

**Pull request merged**
