### PR TITLE
update php 7.4 latest version

### PR DESCRIPTION
**Pull request by samanthajayasinghe**

### CODE REVIEW

**Comment by derschatta** [comment]
is this needed? I thought that 7.4-fpm always gets you the latest version in 7.4?

**Comment by elkbullwinkle** [comment]
This would just hardcode the version to .2

**Comment by derschatta** [comment]
> This would just hardcode the version to .2

I know, but I don't think we need that, it would just create additional work everytime a minor version comes out to update the compose file

**Comment by samanthajayasinghe** [comment]
As I understand, it may not pull latest tag version since it's hardcode to a specific tag(php:7.4-fpm)
if PHP follows semantic versioning then it may pull the latest version with (php:7.4.*) option 

but I'm not really sure that php:7.4-fpm = php:7.4.2-fpm

**Comment by elkbullwinkle** [comment]
Usually a tag without a minor version will point to the latest minor

**Comment by elkbullwinkle** [comment]
php:7.4 points to php:7.4.1 and php:7.4.2 isn't there yet

**Comment by samanthajayasinghe** [comment]
I mean following -fpm tag 
https://hub.docker.com/layers/php/library/php/7.4.2-fpm/images/sha256-11bdce447a48cf9c44f0992c2ccf1ed350495a830bf54050d8fc2a0500a40f95

**Comment by elkbullwinkle** [comment]
I'm sure it points to the latest minor tag. CHeck it out, run phpinfo with the image tagged 7.4

**Comment by samanthajayasinghe** [comment]
alright .. let's re-build the image then..

**Pull request closed without merging**
