### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by A1vinSmith**

### CODE REVIEW

**Review by derschatta — APPROVED** [review]

**Comment by derschatta** [comment]
Sry, @A1vinSmith  can you rebase this fix on the "develop" and fix the conflict?

**Review by derschatta — CHANGES_REQUESTED** [review]
needs rebase from develop branch

**Comment by A1vinSmith** [comment]
sure, will do that

**Comment by A1vinSmith** [comment]
Hi @derschatta , I think i did the rebase? not quite sure how GitHub handling this

**Comment by derschatta** [comment]
@A1vinSmith there's still my  commit in there "Merge branch 'develop' into master" which ideally should be remove. Can you try?

**Comment by A1vinSmith** [comment]
Hi @derschatta, i create a new pr for that. https://github.com/totara/totara-docker-dev/pull/145

**Pull request closed without merging**
